spring.datasource.url=jdbc:mysql://mysql:3306/edufy_db
spring.datasource.username=edman
spring.datasource.password=erik
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak_container:8080/realms/Edufy_Realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak_container:8080/realms/Edufy_Realm/protocol/openid-connect/certs

jwt.auth.converter.resource-id.name=Edufy_Client
jwt.auth.converter.principal-attribute=preferred_username

keycloak.server-url=http://keycloak_container:8080
keycloak.realm=Edufy_Realm
keycloak.client-id=Edufy_Client
keycloak.client-secret=59yWVnUaODRcklUlzRm62iejAmXFNqyY
keycloak.client-uuid=c30fb6c9-d94f-465d-abb5-056fcb582e97
keycloak.default-role-id=4b5414ee-0544-4be6-afa2-36d6efbe4665
keycloak.default-role-name=user

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
