spring.application.name=edufy_userservice
server.address=0.0.0.0
server.port=9999

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Edufy_Realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/Edufy_Realm/protocol/openid-connect/certs

jwt.auth.converter.resource-id.name=Edufy_Client
jwt.auth.converter.principal-attribute=preferred_username

keycloak.server-url=http://localhost:8080
keycloak.realm=Edufy_Realm
keycloak.client-id=Edufy_Client
keycloak.client-secret=59yWVnUaODRcklUlzRm62iejAmXFNqyY
keycloak.client-uuid=c30fb6c9-d94f-465d-abb5-056fcb582e97
keycloak.default-role-id=4b5414ee-0544-4be6-afa2-36d6efbe4665
keycloak.default-role-name=user

logging.level.org.springframework.security=DEBUG

spring.profiles.active=dev


